/** Map exercises to front/back muscle highlights for the body diagram. */
export const EXERCISE_TO_MUSCLES: Record<string, { front: string[]; back: string[] }> = {
  "Barbell Bench Press": { front: ["chest", "pecs", "triceps", "delts"], back: ["triceps"] },
  "Dumbbell Bench Press": { front: ["chest", "pecs", "triceps", "delts"], back: ["triceps"] },
  "Incline Bench Press": { front: ["chest", "pecs", "delts", "triceps"], back: ["triceps"] },
  "Decline Bench Press": { front: ["chest", "pecs", "triceps", "delts"], back: ["triceps"] },
  "Push-Ups": { front: ["chest", "pecs", "triceps", "delts", "abs"], back: ["triceps"] },
  "Cable Chest Fly": { front: ["chest", "pecs"], back: [] },
  "Dumbbell Chest Fly": { front: ["chest", "pecs", "delts"], back: [] },
  "Pec Deck Machine": { front: ["chest", "pecs"], back: [] },
  "Chest Press Machine": { front: ["chest", "pecs", "triceps", "delts"], back: ["triceps"] },
  "Pec Fly Machine": { front: ["chest", "pecs"], back: [] },
  "Lat Pullover Machine": { front: ["chest", "pecs"], back: ["lats", "latissimus"] },
  "Barbell Bicep Curl": { front: ["biceps"], back: [] },
  "Dumbbell Bicep Curl": { front: ["biceps"], back: [] },
  "Hammer Curl": { front: ["biceps", "forearms"], back: [] },
  "Preacher Curl": { front: ["biceps"], back: [] },
  "Concentration Curl": { front: ["biceps"], back: [] },
  "Cable Curl": { front: ["biceps"], back: [] },
  "Incline Dumbbell Curl": { front: ["biceps"], back: [] },
  "EZ Bar Curl": { front: ["biceps", "forearms"], back: [] },
  "Overhead Tricep Extension (Dumbbell)": { front: ["triceps"], back: ["triceps"] },
  "Overhead Tricep Extension (Cable)": { front: ["triceps"], back: ["triceps"] },
  "Skull Crushers": { front: ["triceps"], back: ["triceps"] },
  "Tricep Kickbacks": { front: ["triceps"], back: ["triceps"] },
  "Close-Grip Bench Press": { front: ["triceps", "chest", "pecs", "delts"], back: ["triceps"] },
  Dips: { front: ["triceps", "chest", "pecs", "delts"], back: ["triceps"] },
  "Machine Tricep Pushdown": { front: ["triceps"], back: ["triceps"] },
  "Rope Tricep Pushdown": { front: ["triceps"], back: ["triceps"] },
  "Dumbbell Shoulder Press": { front: ["delts", "triceps"], back: ["delts", "triceps"] },
  "Barbell Shoulder Press (Overhead Press)": { front: ["delts", "triceps"], back: ["delts", "triceps", "traps", "trapezius"] },
  "Arnold Press": { front: ["delts", "triceps"], back: ["delts", "triceps"] },
  "Lateral Raise": { front: ["delts"], back: ["delts"] },
  "Front Raise": { front: ["delts"], back: [] },
  "Rear Delt Fly": { front: [], back: ["delts"] },
  "Cable Lateral Raise": { front: ["delts"], back: ["delts"] },
  "Cable Front Raise": { front: ["delts"], back: [] },
  "Cable Rear Delt Fly": { front: [], back: ["delts", "traps", "trapezius"] },
  "Cable Face Pull with Rope": { front: [], back: ["delts", "traps", "trapezius"] },
  "Shoulder Press Machine": { front: ["delts", "triceps"], back: ["delts", "triceps"] },
  "Barbell Row": { front: ["biceps"], back: ["lats", "latissimus", "traps", "trapezius", "biceps"] },
  "Dumbbell Row": { front: ["biceps"], back: ["lats", "latissimus", "traps", "trapezius", "biceps"] },
  "T-Bar Row": { front: ["biceps"], back: ["lats", "latissimus", "traps", "trapezius", "biceps"] },
  "Seated Cable Row": { front: ["biceps"], back: ["lats", "latissimus", "traps", "trapezius", "biceps"] },
  "Lat Pulldown": { front: ["biceps"], back: ["lats", "latissimus", "biceps"] },
  "Pull-Ups": { front: ["biceps"], back: ["lats", "latissimus", "biceps", "delts", "abs"] },
  "Chin-Ups": { front: ["biceps", "forearms"], back: ["lats", "latissimus", "biceps", "abs"] },
  "Inverted Row": { front: ["biceps"], back: ["lats", "latissimus", "traps", "trapezius", "biceps", "delts"] },
  "Face Pulls": { front: [], back: ["delts", "traps", "trapezius"] },
  "Barbell Squat": { front: ["quads", "quadriceps", "abs"], back: ["glutes", "hamstrings"] },
  "Front Squat": { front: ["quads", "quadriceps", "abs"], back: ["glutes"] },
  "Goblet Squat": { front: ["quads", "quadriceps", "abs"], back: ["glutes"] },
  "Sumo Squat": { front: ["quads", "quadriceps"], back: ["glutes"] },
  "Leg Press Machine": { front: ["quads", "quadriceps"], back: ["glutes", "hamstrings"] },
  "Lunges (Walking)": { front: ["quads", "quadriceps"], back: ["glutes", "hamstrings"] },
  "Reverse Lunges": { front: ["quads", "quadriceps"], back: ["glutes", "hamstrings"] },
  "Step-Ups": { front: ["quads", "quadriceps"], back: ["glutes", "hamstrings"] },
  "Bulgarian Split Squat": { front: ["quads", "quadriceps"], back: ["glutes", "hamstrings"] },
  "Leg Extension Machine": { front: ["quads", "quadriceps"], back: [] },
  "Hamstring Curl Machine": { front: [], back: ["hamstrings"] },
  "Romanian Deadlift": { front: [], back: ["hamstrings", "glutes"] },
  "Stiff-Leg Deadlift": { front: [], back: ["hamstrings", "glutes"] },
  "Conventional Deadlift": { front: [], back: ["hamstrings", "glutes", "traps", "trapezius"] },
  "Sumo Deadlift": { front: ["quads", "quadriceps"], back: ["glutes", "hamstrings", "traps", "trapezius"] },
  "Jump Squats": { front: ["quads", "quadriceps", "calves"], back: ["glutes", "hamstrings"] },
  "Box Jumps": { front: ["quads", "quadriceps", "calves"], back: ["glutes"] },
  "Leg Curl (Seated)": { front: [], back: ["hamstrings"] },
  "Leg Curl (Lying)": { front: [], back: ["hamstrings"] },
  "Seated Calf Raise": { front: ["calves"], back: ["calves"] },
  "Standing Calf Raise": { front: ["calves"], back: ["calves"] },
  "Donkey Calf Raise": { front: ["calves"], back: ["calves"] },
  "Hip Thrust": { front: [], back: ["glutes", "hamstrings", "abs"] },
  "Glute Bridge": { front: [], back: ["glutes", "hamstrings", "abs"] },
  Plank: { front: ["abs"], back: [] },
  "Side Plank": { front: ["obliques"], back: ["obliques"] },
  "Hanging Leg Raise": { front: ["abs"], back: [] },
  "Cable Crunch": { front: ["abs"], back: [] },
  "Ab Wheel Rollout": { front: ["abs"], back: [] },
  "Russian Twist": { front: ["abs", "obliques"], back: ["obliques"] },
  "Bicycle Crunch": { front: ["abs", "obliques"], back: [] },
  "Mountain Climbers": { front: ["abs"], back: [] },
  "Reverse Crunch": { front: ["abs"], back: [] },
  "Sit-Ups": { front: ["abs"], back: [] },
  "Flutter Kicks": { front: ["abs"], back: [] },
  "Back Extension": { front: [], back: ["glutes", "hamstrings"] },
  "Good Mornings": { front: [], back: ["hamstrings", "glutes"] },
  "Kettlebell Swing": { front: ["abs"], back: ["glutes", "hamstrings", "delts"] },
  "Farmer's Carry": { front: ["forearms", "abs"], back: ["traps", "trapezius"] },
  "Suitcase Carry": { front: ["obliques", "forearms"], back: [] },
  "Sled Push": { front: ["quads", "quadriceps", "calves", "abs"], back: ["glutes"] },
  "Sled Pull": { front: [], back: ["hamstrings", "glutes", "calves", "abs"] },
  "Rowing Machine": { front: ["biceps", "abs"], back: ["lats", "latissimus", "biceps"] },
  "Jump Rope": { front: ["calves", "quads", "quadriceps", "delts"], back: [] },
  "Running on Treadmill": { front: ["quads", "quadriceps"], back: ["glutes"] },
  "Incline Treadmill Walk": { front: ["quads", "quadriceps", "calves"], back: ["glutes"] },
  "Stationary Bike": { front: ["quads", "quadriceps", "calves"], back: ["hamstrings"] },
  Elliptical: { front: ["quads", "quadriceps", "delts"], back: ["glutes"] },
  Burpees: { front: ["chest", "pecs", "quads", "quadriceps", "abs", "delts"], back: [] },
  "Medicine Ball Slam": { front: ["abs", "delts"], back: [] },
  Shrugs: { front: ["traps", "trapezius"], back: ["traps", "trapezius"] },
  "Upright Row": { front: ["delts", "traps", "trapezius", "biceps"], back: ["traps", "trapezius"] },
};
