/** Workout exercises organized by muscle groups. Shared by AddWorkoutPage and WorkoutInputSection. */
export const WORKOUT_BY_MUSCLE_GROUP: Record<string, string[]> = {
  Chest: [
    "Barbell Bench Press",
    "Dumbbell Bench Press",
    "Incline Bench Press",
    "Decline Bench Press",
    "Push-Ups",
    "Cable Chest Fly",
    "Dumbbell Chest Fly",
    "Pec Deck Machine",
    "Chest Press Machine",
    "Pec Fly Machine",
    "Lat Pullover Machine",
  ],
  Arms: [
    "Barbell Bicep Curl",
    "Dumbbell Bicep Curl",
    "Hammer Curl",
    "Preacher Curl",
    "Concentration Curl",
    "Cable Curl",
    "Incline Dumbbell Curl",
    "EZ Bar Curl",
    "Overhead Tricep Extension (Dumbbell)",
    "Overhead Tricep Extension (Cable)",
    "Skull Crushers",
    "Tricep Kickbacks",
    "Close-Grip Bench Press",
    "Dips",
    "Machine Tricep Pushdown",
    "Rope Tricep Pushdown",
  ],
  Shoulders: [
    "Dumbbell Shoulder Press",
    "Barbell Shoulder Press (Overhead Press)",
    "Arnold Press",
    "Lateral Raise",
    "Front Raise",
    "Rear Delt Fly",
    "Cable Lateral Raise",
    "Cable Front Raise",
    "Cable Rear Delt Fly",
    "Cable Face Pull with Rope",
    "Shoulder Press Machine",
  ],
  Back: [
    "Barbell Row",
    "Dumbbell Row",
    "T-Bar Row",
    "Seated Cable Row",
    "Lat Pulldown",
    "Pull-Ups",
    "Chin-Ups",
    "Inverted Row",
    "Face Pulls",
    "Lat Pullover Machine",
  ],
  Legs: [
    "Barbell Squat",
    "Front Squat",
    "Goblet Squat",
    "Sumo Squat",
    "Leg Press Machine",
    "Lunges (Walking)",
    "Reverse Lunges",
    "Step-Ups",
    "Bulgarian Split Squat",
    "Leg Extension Machine",
    "Hamstring Curl Machine",
    "Romanian Deadlift",
    "Stiff-Leg Deadlift",
    "Conventional Deadlift",
    "Sumo Deadlift",
    "Jump Squats",
    "Box Jumps",
    "Leg Curl (Seated)",
    "Leg Curl (Lying)",
  ],
  Glutes: ["Hip Thrust", "Glute Bridge"],
  Calfs: ["Seated Calf Raise", "Standing Calf Raise", "Donkey Calf Raise"],
  Abs: [
    "Plank",
    "Side Plank",
    "Hanging Leg Raise",
    "Cable Crunch",
    "Ab Wheel Rollout",
    "Russian Twist",
    "Bicycle Crunch",
    "Mountain Climbers",
    "Reverse Crunch",
    "Sit-Ups",
    "Flutter Kicks",
    "Back Extension",
    "Good Mornings",
  ],
  Core: [
    "Kettlebell Swing",
    "Farmer's Carry",
    "Suitcase Carry",
    "Sled Push",
    "Sled Pull",
    "Rowing Machine",
    "Jump Rope",
    "Running on Treadmill",
    "Incline Treadmill Walk",
    "Stationary Bike",
    "Elliptical",
    "Burpees",
    "Medicine Ball Slam",
  ],
  Traps: ["Shrugs", "Upright Row"],
};
