-- Rival push notifications infrastructure
-- 1) Stores iOS APNs device tokens
-- 2) Calls Edge Function when workouts/posts are inserted

create extension if not exists pg_net;

create table if not exists public.user_push_tokens (
  id bigint generated by default as identity primary key,
  user_sub_id varchar not null references public.users(sub_id) on delete cascade,
  platform text not null check (platform in ('ios')),
  apns_token text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_sub_id, platform, apns_token)
);

create index if not exists idx_user_push_tokens_user_sub_id
  on public.user_push_tokens(user_sub_id);

create or replace function public.set_user_push_tokens_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_user_push_tokens_updated_at on public.user_push_tokens;
create trigger trg_user_push_tokens_updated_at
before update on public.user_push_tokens
for each row
execute function public.set_user_push_tokens_updated_at();

create or replace function public.notify_rival_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_sub_id text;
  event_type text;
  function_url text := 'https://xfffigdnmqvcjnxqkwdq.supabase.co/functions/v1/rival-activity';
  payload jsonb;
begin
  if tg_table_name = 'workout_sessions' then
    actor_sub_id := new.sub_id;
    event_type := 'workout_logged';
  elsif tg_table_name = 'posts' then
    actor_sub_id := new.user_sub_id;
    event_type := 'post_created';
  else
    return new;
  end if;

  if actor_sub_id is null or actor_sub_id = '' then
    return new;
  end if;

  payload := jsonb_build_object(
    'event_type', event_type,
    'actor_sub_id', actor_sub_id,
    'record', to_jsonb(new)
  );

  perform net.http_post(
    url := function_url,
    headers := '{"Content-Type":"application/json"}'::jsonb,
    body := payload
  );

  return new;
end;
$$;

drop trigger if exists trg_notify_rival_activity_workout on public.workout_sessions;
create trigger trg_notify_rival_activity_workout
after insert on public.workout_sessions
for each row
execute function public.notify_rival_activity();

drop trigger if exists trg_notify_rival_activity_post on public.posts;
create trigger trg_notify_rival_activity_post
after insert on public.posts
for each row
execute function public.notify_rival_activity();
